### ISSUE TITLE
library.properties missing ?

### ISSUE THREAD

**Issue by pagaille** [karol-brejna-i/RemoteDebug#5]
I'm using IDE 2.1.1 and can't add your library. Arduino IDE doesn't recognize it in the `libraries` folder. Could it be that the file `library.properties` is missing ?

**Comment by karol-brejna-i** [comment]
I have not been using Arduino IDE for ages now. Let me check what condition the library needs to meet to "show up" in the IDE. @pagaille Thanks for pointing this out.

**Comment by karol-brejna-i** [comment]
The publication process (for the library to be included in the Arduino registry) may take a while).
I'll let you know when I can confirm this.

**Comment by karol-brejna-i** [comment]
It looks like Arduino IDE/registry is using simplistic "dependncy management". It won't accept library with the same name (even if it comes from other vendor, i.e. JoaoLopesF/RemoteDebug vs karol-brejna-i/RemoteDebug):

```
ERROR: Library name RemoteDebug is in use by a library in the Library Manager index. Each library must have a unique    
       name value. If your library is already in the index, use the "--library-manager update" flag.
```
(see: https://github.com/arduino/library-registry/pull/3823)

To work around this problem I'll probably "invent" some new name for the library (only for `library.properties`).

**Comment by karol-brejna-i** [comment]
The library has been registered as `RemoteDebug2` (https://www.arduino.cc/reference/en/libraries/remotedebug2/).
@pagaille Could you take a look if you are able to use it?

**Comment by pagaille** [comment]
<img width="211" alt="image" src="https://github.com/karol-brejna-i/RemoteDebug/assets/1886799/31862cc5-0954-44e2-9bca-291dcbb2a6b7">

Success. Can't wait to try it out, no ESP right now to test. Thanks again, and happy new year 😊
